### ISSUE TITLE
PHP Fatal Error when synced locally

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/content.uiowa.edu#1]
## Error
```console
PHP Fatal error:  Cannot redeclare paragraphs_features_export_options() (previously declared in .../contrib/paragraphs/paragraphs.features.inc:11) in .../contrib/paragraphs/paragraphs.features.inc on line 18
```

## Steps to reproduce
1 - Sync down site from prod
2 - Clear cache via drush

**Comment by adamdelaney** [comment]
Manually truncating all cache tables seems to resolve this problem. May want to look into doing this in production.

**Comment by markahrens** [comment]
This is an issue with having a local copy of paragraphs in this repo. I don't know if it is because of the way paragraphs is structured or how features is structured. My work around for it has been removing the paragraphs.features.inc file from the local modules folder, clearing cache, then moving the folder back.
